version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: graade
      POSTGRES_PASSWORD: senha@123
      POSTGRES_DB: graade
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
